### ISSUE TITLE
New version v0.52.0 for windows crate

### ISSUE THREAD

**Issue by wischi-chr** [zdimension/variant-rs#3]
Because there is a new windows crate version v0.52.0 (this crate is currently based on v0.48.0) the re-exported `VARIANT` type is incompatible (similar to what happened in #1).

I just cloned the repository locally and tried to update it.

Most things were pretty trivial.

![image](https://github.com/zdimension/variant-rs/assets/2495113/488cb959-5806-43a9-9cae-a4a0d17aa208)

The namespace changed for `VARIANT` and `VARENUM`

![image](https://github.com/zdimension/variant-rs/assets/2495113/a0beac42-c344-4481-ae92-ad517bca7cd6)

but the rust compiler complained about the `impl From<&VARIANT_BOOL> for &'static mut ComBool` block in `src/com_types/bool.rs` because it's undefined behavior to cast a reference to a mutable reference even if the reference is never used.

I'm my use-case I didn't need that part, so I just commented it out. This right there was the reason why I didn't create a PR with the changes because I have no idea how to fix that issue and I didn't want to introduce backwards incompatible changes.

Thank you so much for your crate, the `VARIANT` type from the auto-generated windows crate would be practically unusable without your crate.

**Comment by zdimension** [comment]
Thanks for the heads-up, I just published version 0.4.0 on crates.io with all dependencies updated including `windows` 0.52.0!

**Comment by wischi-chr** [comment]
Wow that was fast. Thank you.
